/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:bc05c7b8-c9c0-4c04-ae6f-7b4cbb5008cd",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_czi1VJacn",
    "aws_user_pools_web_client_id": "1rub150du4shi4jvu5tkegvlu9",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://p3myqnroanalhlq7mm6wleprwq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-7q3mfedngjg25edrtz24jossg4",
    "aws_user_files_s3_bucket": "imagestoragebucket54717-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
